name: Update Scott Hasn't Seen Radarr List

on:
  schedule:
    # Run daily at 2 AM UTC
    - cron: '0 2 * * *'
  workflow_dispatch: # Allow manual triggering
  push:
    branches:
      - main
    paths-ignore:
      - 'scott_hasnt_seen.json' # Don't trigger on JSON updates to avoid loops

jobs:
  update-list:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
        
    - name: Install dependencies
      run: |
        cd .github/scripts
        go mod download
        go mod verify
        
    - name: Run tests
      run: |
        cd .github/scripts
        go test -v
        
    - name: Run scraper
      env:
        TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }}
      run: |
        cd .github/scripts
        go run main.go
        
    - name: Verify JSON file
      run: |
        echo "Checking if scott_hasnt_seen.json was created/updated:"
        if [ -f "scott_hasnt_seen.json" ]; then
          echo "File exists. Size: $(wc -l < scott_hasnt_seen.json) lines"
          echo "First few lines:"
          head -10 scott_hasnt_seen.json
        else
          echo "File does not exist!"
        fi
      
    - name: Check for changes
      id: changes
      run: |
        # Debug: Show current directory and file status
        echo "Current directory: $(pwd)"
        echo "Files in current directory:"
        ls -la
        echo ""
        echo "Git status:"
        git status
        echo ""
        
        # Check if the JSON file was modified by the scraper
        if git diff --quiet scott_hasnt_seen.json; then
          echo "changed=false" >> $GITHUB_OUTPUT
          echo "No changes detected in scott_hasnt_seen.json"
        else
          echo "changed=true" >> $GITHUB_OUTPUT
          echo "Changes detected in scott_hasnt_seen.json"
          git diff --stat scott_hasnt_seen.json
        fi
        
    - name: Commit and push changes
      if: steps.changes.outputs.changed == 'true'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add scott_hasnt_seen.json
        git commit -m "Update Scott Hasn't Seen list - $(date +'%Y-%m-%d')"
        git push
        
    - name: Create release if new movies found
      if: steps.changes.outputs.changed == 'true'
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v$(date +'%Y.%m.%d')
        name: "Scott Hasn't Seen Radarr List - $(date +'%Y-%m-%d')"
        body: |
          Updated Scott Hasn't Seen list with latest movies from the podcast.
          
          This list can be imported into Radarr to automatically add movies that Scott Aukerman has watched on his podcast.
        files: scott_hasnt_seen.json
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 